# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 00:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('DOB', models.DateField()),
                ('gender', models.CharField(blank=True, max_length=120, null=True)),
                ('school_name', models.CharField(blank=True, max_length=120, null=True)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_phone', models.IntegerField()),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
