# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_addsubject_addtheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addsubject',
            name='subjectfile',
            field=models.FileField(upload_to='subject'),
        ),
        migrations.AlterField(
            model_name='addtheme',
            name='themefile',
            field=models.FileField(upload_to='theme'),
        ),
    ]
