# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160605_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
