# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 14:46
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160605_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addsubject',
            name='subjectfile',
            field=models.FileField(upload_to=app.models.subject_content_file_name),
        ),
        migrations.AlterField(
            model_name='addtheme',
            name='themefile',
            field=models.FileField(upload_to=app.models.theme_content_file_name),
        ),
    ]
