# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160610_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='compatibilitymatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectname', models.CharField(max_length=100)),
                ('themename', models.CharField(max_length=100)),
            ],
        ),
    ]
