# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_compatibilitymatrix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='parent_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='parent_phone',
            field=models.IntegerField(null=True),
        ),
    ]
