# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20160622_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompatibilityMatricesMaths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectname', models.CharField(max_length=100)),
                ('themename', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Compatibilty Matrices (Maths)',
                'verbose_name': 'Compatibility Matrix (Maths)',
            },
        ),
        migrations.RenameModel(
            old_name='CompatibilityMatrices',
            new_name='CompatibilityMatricesBrain',
        ),
        migrations.AlterModelOptions(
            name='addsubject',
            options={'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterModelOptions(
            name='addtheme',
            options={'verbose_name': 'Theme', 'verbose_name_plural': 'Themes'},
        ),
        migrations.AlterModelOptions(
            name='compatibilitymatricesbrain',
            options={'verbose_name': 'Compatibility Matrix (Brain)', 'verbose_name_plural': 'Compatibilty Matrices (Brain)'},
        ),
    ]
