# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20160623_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compatibilitymatricesmaths',
            options={'verbose_name': 'Compatibility Matrix (Math)', 'verbose_name_plural': 'Compatibilty Matrices (Math)'},
        ),
    ]
