# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20160623_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchUploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('data_excel_file', models.FileField(upload_to='/temp/')),
            ],
        ),
    ]
