# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_batchuploadmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchuploadmodel',
            name='filename',
        ),
    ]
