# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 17:50
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_batchuploadmodel_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchuploadmodel',
            name='data_excel_file',
            field=models.FileField(upload_to=app.models.batchfileuploadpath),
        ),
    ]
