# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 20:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_report_sent',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 30, 20, 18, 35, 895310)),
        ),
    ]
