# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-07 11:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20161007_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_report_sent',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 7, 11, 25, 26, 479412)),
        ),
    ]
